<div class="page_title">
    <h1><?php echo $this->__("Hello World Revenge"); ?></h1> <!-- underscore indica di effettuare la traduzione -->
</div>
<div class="content">
    <?php if ($this->isEnabled()) : ?>
        <p><?php echo $this->__("Welcome to the Hello World Revenge Module"); ?></p>
        <?php if ($this->getMessage()) : ?>
            <p><?php echo $this->getMessage(); ?></p>
        <?php endif; ?>
    <?php endif; ?>
</div>